name: pharmax
description: "PharmaX - نظام ذكي لإدارة الصيدليات"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  mobile_scanner: ^7.0.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  desktop_multi_window: ^0.2.0
  window_manager: ^0.3.8

  # إدارة الحالة
  provider: ^6.1.1

  # قاعدة البيانات المحلية (Drift)
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.21
  path_provider: ^2.1.2
  path: ^1.9.0
  printing: ^5.13.0
  pdf: ^3.10.8
  barcode_widget: ^2.0.4
  data_table_2: ^2.5.9
  


  # حوارات ذكية
  flutter_typeahead: ^5.2.0

  # التواريخ والأرقام
  intl: ^0.20.2

  # جداول احترافية


  # أيقونات إضافية
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  drift_dev: ^2.16.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
